pipeline {
    environment {
        PATH = "$PATH:/usr/bin"
    }
    
    agent any
    stages {
        
        stage('Initial Cleanup') {
          steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        
        stage('Cloning Git repository') {
          steps {
                git branch : 'main', url: 'https://github.com/TheCountt/docker-php-todo.git'
            }
        }

        

        
        stage("Start the app") {
            steps {

                        sh "docker-compose --version"
                        sh "docker-compose up -d"
                    }
		        }

        stage("Test endpoint") {
            steps {
                script {
                        def response = httpRequest "http://localhost:8000"
                        println("Status: "+response.status)
                        println("Content: "+response.content)

                        
                    
                } 
            }
        }
    }
}